# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        gramc_provider:
             id: app.gramc_user_provider
                # if you're using multiple entity managers
                # manager_name: customer
        in_memory:
            memory:
                users:
                    consoupload:
                       password: '%env(PASSWORD_CONSOUPLOAD)%'
                       roles: 'ROLE_ADMIN'
        #user_provider:
        #    id: app.user_provider
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|icones|js)/
            security: false

        consoupload:
            pattern:   ^/adminux
            http_basic:
                  provider: in_memory

        main:
            pattern:    ^/
            context: global_security_context
            user_checker: app.user_checker
            switch_user: true
            provider: gramc_provider
            #security: false
            anonymous: ~
            remote_user:
                provider: gramc_provider
            #logout:
            #    path:   /deconnexion
            #    target: /deconnected

    access_control:
       - { path: ^/none, roles: ROLE_DEMANDEUR }


